## Load configurations 
source('GlobalVars.R')

## Find euclidean distances for two sets of 2D points. Returns a vector 
## with distances for each of the corresponding rows in the sets

euclideanDistances <- function(pointsSet1, pointsSet2) {
	if (length(pointsSet1)!=length(pointsSet2)) {
		stop("Invalid input: lengths of the vectors are not equal");
	}
	xDist = pointsSet1[, 1]-pointsSet2[, 1]
	yDist = pointsSet1[, 2]-pointsSet2[, 2]
	eucDist = sqrt(xDist*xDist+yDist*yDist)
	eucDist
}

## Copies all the files from a source to a target directory 

copyAllFiles <- function(sourceDirectory, targetDirectory) {
	files <- list.files(sourceDirectory, recursive = FALSE);
	lapply(files, 
		function(filePath) {
		path = paste(sourceDirectory, filePath, sep="")
		file.copy(from=path, to=targetDirectory)
    }
  )
}

## Processes the Cohn-Kanade data set and returns a list of paths to labeled emotion files
## Example: findLabeledEmotionFiles(emotionLabels$happy)

findLabeledEmotionFiles <- function(emotionCode, folder = emotionLabelsFolder) {
	files <- list.files(folder, recursive = TRUE)
	emotionLabelsFiles <- c(); 
	lapply(files, 
		function(file) {
			path = paste(folder, file, sep="/")
			if (read.table(path)==emotionCode) {
				emotionLabelsFiles <<- c(emotionLabelsFiles, path)
			}
		}
	)
	emotionLabelsFiles
}


## Processes the Cohn-Kanade data set, extracting the most relevant landmarks files 
## for a particular facial expression
## Example: findAndCopyEmotionFiles(emotionLabels$happy)

findAndCopyEmotionFiles <- function(emotionCode, targetDirectory = outputFolder) {
	files <- findLabeledEmotionFiles(emotionCode);
	lapply(files, 
		function(path) {
			sPos <- regexpr("S[[:digit:]][[:digit:]][[:digit:]]/", path)   
			endPos <- regexpr("/[[:digit:]][[:digit:]][[:digit:]]/", path)
			if (endPos!=-1) {
				endPos <- endPos+4
				copyFromFolder <- substring(path, sPos, endPos)
				copyFromFolder <- paste(landmarksFolder, copyFromFolder, sep="/")
				copyToFolder   <- substring(path, sPos, endPos-4-1)
				newFolderFullPath <- paste(targetDirectory, copyToFolder, sep="/")
				if (!file.exists(newFolderFullPath)) {
					dir.create(newFolderFullPath)
				}
				copyAllFiles(copyFromFolder, newFolderFullPath)
				paste(copyFromFolder, newFolderFullPath, sep="=>")
			} else {
				NA
			}
		}
	)
}

## Creates a set of folders, specified in @folderPathsList, within the @targetDirectory   

createFolders <- function(folderPathsList = emotionFolders, targetDirectory = outputFolder) {
	lapply(folderPathsList, 
		function(folderPath) {
			if (!file.exists(folderPath)) {
				dir.create(folderPath)
			} 
		}
	)
} 
	
## Processes the list of files, generated by findAndCopyEmotionFiles() function,  
## generating n.dat (netral face landmarks) and em.dat (emotional face landmarks) files for each subject 

preprocessEmotionFilePaths <- function(inputFolderPath = happinessFolder) {
	folders <- list.dirs(inputFolderPath, recursive = FALSE)
	lapply(folders, 
		function(folder) { 
			files <- list.files(folder, recursive = FALSE);
			firstFile = paste(folder, files[1], sep="/"); 
			lastFile = paste(folder, files[length(files)], sep="/"); 
			file.copy(from=firstFile, to=paste(folder, "n.dat", sep="/"));
			file.copy(from=lastFile,  to=paste(folder, "em.dat", sep="/"));
		}
	)
}

## Processes landmarks files within the input folder, generating normalized_change.dat 
## file with normalized change between landmarks in n.dat and em.dat files

createNormalizedLandmarkFiles <-function(inputFolderPath = happinessFolder) {
	folders <- list.dirs(inputFolderPath, recursive = FALSE)
	lapply(folders, 
		  function(folder) { 
		  	neutralFace   <- read.table(paste(folder,"n.dat", sep="/"))
		  	emotionalFace <- read.table(paste(folder,"em.dat", sep="/"))
		  	distances     <- euclideanDistances(neutralFace, emotionalFace)
		  	normalizedDistances <- normalize(distances)
		  	destinationPath = paste(folder, "normalized_distances.dat", sep="/")
		  	normalizedDistances
		  	file.create(destinationPath, overwrite=TRUE)
		  	write(normalizedDistances, file=destinationPath, ncolumns=1000)
		  }
	)
}

normalize <- function(array) {
	s <- sqrt(var(array))
	normalizedArray <- (array-mean(array)) / s
	normalizedArray
}

## Generates a graph representing average landmarks change between neutral and emotional faces from the Cohn-Kanade data set

plotLandmarkChangesSummary <- function() {
	res <- analyzeFaceExpressions()
	Landmark_ID <- 1:length(res)
	Average_Change <- res
	plot(Landmark_ID, Average_Change, col=ifelse(Average_Change>=9, "red", "black"), lwd=4, type='p')
}

## * Part 1: Read input files that describe landmarks positions for neutral and emotional faces
## Reads files in the following way:
## 	1) Scans all the folders in the input folder 
## 	2) Searches for n.dat and em.dat files that store neutral and an emotional expressions
## * Part 2: Find average landmarks change across all the faces 

analyzeFaceExpressions <- function(inputFolderPath = happinessFolder) {
	landmarksFolders <- list.dirs(inputFolderPath, recursive = FALSE)
	sum          <- list()
	neutralSum   <- list()
	emotionalSum <- list()
	cnt <- 1
	     
	lapply(landmarksFolders, 
		function(folder) {
			neutralFace   <- read.table(paste(folder,"n.dat", sep="/"))
			emotionalFace <- read.table(paste(folder,"em.dat", sep="/"))
			distances     <- euclideanDistances(neutralFace, emotionalFace)
			if (cnt==1) {
				sum             <<- distances
				neutralSum      <<- neutralFace
				emotionalSum    <<- emotionalFace
			} else {
				sum          <<- sum + distances
				neutralSum   <<- neutralSum + neutralFace
				emotionalSum <<- emotionalSum + emotionalFace
			}
			cnt <<- cnt + 1
		}
	)
	## Obtain the average change of landmarks across all faces
	neutralAvg     <- neutralSum / cnt
	emotionalAvg   <- emotionalSum / cnt  
  
	## Constructing Face maps - visualization characterizing average changes of landmarks across all faces 
	dataToPlot <- neutralAvg
	dataToPlot <- rbind(dataToPlot, emotionalAvg)
	len <- nrow(dataToPlot)
	dataToPlot <- cbind(dataToPlot, rowId=1:len)
	plot(dataToPlot[, 1], -dataToPlot[, 2], col=ifelse(dataToPlot$rowId > len/2, "red", "black"), lwd=4, type='p')
  
	## Visualizations:
	## plot(neutralAvg[, 1], neutralAvg[, 2])
	## plot(emotionalAvg[, 1], emotionalAvg[, 2])
	## plot(AU_ID, Average_Change, col=ifelse(Average_Change>=9, "orange", "black"), lwd=4, type='p')
  
	## Obtain the average change of landmarks across all faces
	totalAvg <- sum / cnt
	totalAvg
}