## Global variables 
emotionLabelsFolder   <- "C:/Users/user/Documents/Docs_HP/TUM/Semester II/Data Mining Praktikum/FER Dataset/Data provided/CK+/Emotion_labels/Emotion"
landmarksFolder       <- "C:/Users/user/Documents/Docs_HP/TUM/Semester II/Data Mining Praktikum/FER Dataset/Data provided/CK+/Landmarks/Landmarks"
AULabelsFolder        <- "C:/Users/user/Documents/Docs_HP/TUM/Semester II/Data Mining Praktikum/FER Dataset/Data provided/CK+/FACS_labels/FACS"
faceExpressionsFolder <- "C:/Users/user/Documents/Docs_HP/TUM/Semester II/Data Mining Praktikum/FER Dataset/W2. Feature Extraction/Face expressions"
outputFolder          <- "Observations"

## Find euclidean distances for two sets of 2D points. Returns a vector 
## with distances for each of the corresponding rows in the sets

euclideanDistances <- function(pointsSet1, pointsSet2) {
	if (length(pointsSet1)!=length(pointsSet2)) {
		stop("Invalid input: lengths of the vectors are not equal");
	}
	xDist = pointsSet1[, 1]-pointsSet2[, 1]
	yDist = pointsSet1[, 2]-pointsSet2[, 2]
	eucDist = sqrt(xDist*xDist+yDist*yDist)
	eucDist
}

## Lists subfolders within a given folder

listFolders <- function(inputFolderPath) {
	path = paste(".", inputFolderPath, sep="/")
	list.dirs(path, recursive = FALSE)
}

## Copies all the files from a source to a target directory 

copyAllFiles <- function(sourceDirectory, targetDirectory) {
  files <- list.files(sourceDirectory, recursive = FALSE);
  lapply(files, 
    function(filePath) {
      path = paste(sourceDirectory, filePath, sep="")
      file.copy(from=path, to=targetDirectory)
    }
  )
}

## Processes the Cohn-Kanade data set and returns a list of 
## paths to labeled emotion files, related to happiness

findLabeledHappinessFiles <- function() {
  files <- list.files(emotionLabelsFolder, recursive = TRUE)
  happinessLabelsFiles <- c(); 
  lapply(files, 
    function(file) {
      path = paste(emotionLabelsFolder, file, sep="/")
      if (read.table(path)==5) {
        happinessLabelsFiles <<- c(happinessLabelsFiles, path)
      }
    }
  )
  happinessLabelsFiles
}


## Processes the Cohn-Kanade data set, extracting the most relevant landmarks files 
## for the task of happiness recognition

findAndCopyHappinessFiles <- function(targetDirectory = outputFolder) {
  files <- findLabeledHappinessFiles();
  lapply(files, 
    function(path) {
      sPos <- regexpr("S[[:digit:]][[:digit:]][[:digit:]]/", path)   
      endPos <- regexpr("/[[:digit:]][[:digit:]][[:digit:]]/", path)
      if (endPos!=-1) {
        endPos <- endPos+4
        copyFromFolder <- substring(path, sPos, endPos)
        copyFromFolder <- paste(landmarksFolder, copyFromFolder, sep="/")
        copyToFolder   <- substring(path, sPos, endPos-4-1)
        newFolderFullPath <- paste(targetDirectory, copyToFolder, sep="/")
        if (!file.exists(newFolderFullPath)) {
          dir.create(newFolderFullPath)
        }
        copyAllFiles(copyFromFolder, newFolderFullPath)
        paste(copyFromFolder, newFolderFullPath, sep="=>")
      } else {
        NA
      }
    }
  )
}
	
## Processes the list of files, generated by findAndCopyHappinessFiles() function,  
## generating n.dat (netral face landmarks) and h.dat (happy face landmarks) files for each subject 

preprocessHappinessFilePaths <- function(inputFolderPath = faceExpressionsFolder) {
  folders <- list.dirs(faceExpressionsFolder)
  lapply(folders, 
	function(folder) { 
      files <- list.files(folder, recursive = FALSE);
      firstFile = paste(folder, files[1], sep="/"); 
      lastFile = paste(folder, files[length(files)], sep="/"); 
      file.copy(from=firstFile, to=paste(folder, "n.dat", sep="/"));
      file.copy(from=lastFile,  to=paste(folder, "h.dat", sep="/"));
		}
	)
}

## Generates a graph representing average landmarks change between neutral and happy faces from the Cohn-Kanade data set

plotLandmarkChangesSummary <- function() {
  res<-analyzeFaceExpressions()
  Landmark_ID <- 1:length(res)
  Average_Change <- res
  plot(Landmark_ID, Average_Change, col=ifelse(Average_Change>=9, "red", "black"), lwd=4, type='p')
}
 
## * Part 1: Read input files that describe landmarks positions for neutral and happy faces
## Reads files in the following way:
## 1) Scans all the folders in the input folder 
## 2) Searches for n.dat and h.dat files that store neutral and happiness expressions 
## * Part 2: Find average landmarks change across all the faces 

analyzeFaceExpressions <- function(inputFolderPath = "Face expressions") {
  landmarksFolders <- listFolders(inputFolderPath)
  sum        <- list()
  neutralSum <- list()
  happySum   <- list()
  cnt <- 1
	
  lapply(landmarksFolders, 
    function(folder) {
        neutralFace <- read.table(paste(folder,"n.dat", sep="/"))
        happyFace   <- read.table(paste(folder,"h.dat", sep="/"))
        distances   <- euclideanDistances(neutralFace, happyFace)
        if (cnt==1) {
          sum         <<- distances
          neutralSum  <<- neutralFace
          happySum    <<- happyFace
        } else {
          sum         <<- sum + distances
          neutralSum  <<- neutralSum + neutralFace
          happySum    <<- happySum   + happyFace
        }
        cnt <<- cnt + 1
    }
  )
  
  ## Obtain the average change of landmarks across all faces
  neutralAvg <- neutralSum / cnt
  happyAvg   <- happySum / cnt  
  
  dataToPlot <- neutralAvg
  dataToPlot <- rbind(dataToPlot, happyAvg)
  len <- nrow(dataToPlot)
  dataToPlot <- cbind(dataToPlot, rowId=1:len)
  plot(dataToPlot[, 1], -dataToPlot[, 2], col=ifelse(dataToPlot$rowId > len/2, "red", "black"), lwd=4, type='p')
  
  #plot(neutralAvg[, 1], neutralAvg[, 2])
  #plot(happyAvg[, 1], happyAvg[, 2])
  #plot(AU_ID, Average_Change, col=ifelse(Average_Change>=9, "orange", "black"), lwd=4, type='p')
  
  ## Obtain the average change of landmarks across all faces
  totalAvg <- sum / cnt
  totalAvg
}